name: GameHumour
favicon: null
layout_spectrum: 0.611748012714088
typography_spectrum: 0.789293767651543
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.091913559474051
  lightness: 0.2406200673431158
  saturation: 0.32897830195724964
  rhythmicContrast: 0.2913279081694782
purpose: []
